on:
  push:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2.8.0
      - name: Run clippy
        continue-on-error: true
        run: cargo clippy --all -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2.8.0
      - name: Run rustfmt
        continue-on-error: true
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.8.0
      - name: Run tests
        run: cargo test --all

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: jacobsvante/cargo-deny-action@v1
