name: Create PRs for pricing changes

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 * * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  detect-changed-pricing-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.8.0
      - name: Run & report
        run: |
          cargo build -p updates --release
          ./target/release/updates check-all | tee output.log \
          && grep ERROR output.log \
            | (tr '\n' '\0' \
            | xargs -0 -n1 echo ::error) \
          && rm output.log
      - name: Detect changed extracted texts
        id: detect
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git diff --name-only > all_changed_files.txt
          cat all_changed_files.txt

          CHANGED=$(git diff --name-only results/*/*.extracted.txt)

          echo "Changed extracted texts:"
          echo "$CHANGED"

          # Export as JSON array for matrix
          echo "extracted-txt-files=$(jq -nc --arg str "$CHANGED" '$str | split("\n") | map(select(. != ""))')" >> $GITHUB_OUTPUT

      - name: Upload changed files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          retention-days: 1
          path: |
            $(cat all_changed_files.txt)

    outputs:
      extracted-txt-files: ${{ steps.detect.outputs.extracted-txt-files }}

  create-prs:
    needs: detect-changed-pricing-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extracted-txt-filepath: ${{ fromJson(needs.detect-changed-pricing-pages.outputs.extracted-txt-files) }}
    steps:

      - name: Derive VAT number
        id: clean
        run: |
          FILE="${{ matrix.extracted-txt-filepath }}"
          BASENAME=$(basename "$FILE")
          VAT="${BASENAME%%-*}"   # everything before the first dash
          echo "vat=$VAT"
          echo "vat=$VAT" >> $GITHUB_OUTPUT

      - name: Download changed files
        uses: actions/download-artifact@v4
        with:
          name: changed-files
      - run: git status; git diff --name-only; exit 1
