name: Create PRs for pricing changes

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 * * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  detect-changed-pricing-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.8.0
      - name: Run & report
        run: |
          cargo build -p updates --release
          ./target/release/updates check-all | tee output.log \
          && grep ERROR output.log \
            | (tr '\n' '\0' \
            | xargs -0 -n1 echo ::error) \
          && rm output.log

      - name: Detect changed extracted texts
        id: detect
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          CHANGED=$(git diff --name-only results/*/*.extracted.txt)

          echo "Changed extracted texts:"
          echo "$CHANGED"

          # Export as JSON array for matrix
          echo "extracted-txt-files=$(jq -nc --arg str "$CHANGED" '$str | split("\n") | map(select(. != ""))')" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed-files
        run: |
          git diff --name-only > changed_files.txt
          # Display changed files
          echo "Changed files:"
          cat changed_files.txt

          # Check if there are any changed files
          if [ -s changed_files.txt ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create directory for changed files
        if: steps.changed-files.outputs.has_changes == 'true'
        run: |
          mkdir -p changed-files-artifact

          # Copy each changed file to the artifact directory while preserving structure
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              # Create directory structure in artifact folder
              mkdir -p "changed-files-artifact/$(dirname "$file")"
              cp "$file" "changed-files-artifact/$file"
              echo "Copied: $file"
            fi
          done < changed_files.txt

      - name: Upload changed files as artifact
        if: steps.changed-files.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: changed-files-${{ github.run_id }}
          path: changed-files-artifact/
          retention-days: 1

    outputs:
      extracted-txt-files: ${{ steps.detect.outputs.extracted-txt-files }}

  create-prs:
    needs: detect-changed-pricing-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extracted-txt-filepath: ${{ fromJson(needs.detect-changed-pricing-pages.outputs.extracted-txt-files) }}
    steps:

      - name: Derive VAT number
        id: extract
        run: |
          FILEPATH="${{ matrix.extracted-txt-filepath }}"
          BASENAME=$(basename "$FILEPATH")
          VAT="${BASENAME%%-*}"   # everything before the first dash
          echo "vat=$VAT"
          echo "vat=$VAT" >> $GITHUB_OUTPUT

          FILENAME_BASE="${FILEPATH%.extracted.txt}"
          echo "filename_base=$FILENAME_BASE"
          echo "filename_base=$FILENAME_BASE" >> $GITHUB_OUTPUT

      - name: Download changed files
        uses: actions/download-artifact@v4
        with:
          name: changed-files-${{ github.run_id }}
      - run: |
          echo BEFORE
          pwd
          ls -ahl
          echo AFTER
          mv changed-files-artifact/${{ steps.extract.outputs.filename_base }}* .
          rm -rf changed-files-artifact
          ls -ahl
